Support a non-exiting run mode
fermyon/conformance-tests pull request #39
Opened 2024-10-01 00:41 UTC by itowlson

The Spin runtime tests use `conformance-tests` as a library (https://github.com/fermyon/spin/blob/967fdf368612478cef176bccc491faffad680050/tests/runtime.rs#L31).  However, `run_tests` entry point calls `libmimic::Conclusion::exit()`, which causes the test process to exit at the end of the tests, with the result of the `libmimic` tests _only_.  This means that if a Spin runtime test fails but all conformance tests succeed, the overall test suite still passes, disguising the test failure unless the avid reader pores over the logs.

This PR proposes splitting the `run_tests` entry point into `run_tests_and_exit`, which retains the current behaviour, and `run_tests_to_conclusion`, which instead returns the Conclusion object.  `libmimic` still prints all progress and results as normal.

With this in place, the Spin runtime test that checks conformance will be able to examine `Conclusion::has_failed` and propagate failure (e.g. by returning an error such as "One or more conformance tests failed") or pass on success, without interfering with other tests.

Of course the names and behaviour are totally up for grabs (some names are deliberate to make consumers aware of changed behaviour, but that may be misguided), and if you feel there's a better way of managing this then please feel free to circular-file this - I'm not at all familiar with the code base or with other use cases I'm afraid.

2024-10-07 07:58 UTC, rylev requested changes
I think this is overall a good idea. I think it would personally be better to keep the naming the same and just move everything to return a `libtest_mimic::Conclusion`. The caller then just needs to call `.exit()` if that's their desired behavior. I think that accomplishes everything we want here without making the public API surface more complicated or verbose. What do you think?

2024-10-07 18:19 UTC, itowlson commented
@rylev My concern with that was that a consumer who was calling `run_tests` and relying on the exit behaviour in the `Ok` case would get no hint that they now needed to call `exit()` themselves.  Changing the name would give them a compilation error alerting them that something had changed.  I agree having a function that called `exit` for them was probably excessive though!

But I'm guessing from your comment that we (you) know and control all consumers and this won't be an issue!  So I've set the name back as you suggest with just the change to the return type.

2024-10-08 18:27 UTC, itowlson commented
@rylev I know you have other things going on but do you have a moment to look at this please?  It should be a quick yes/no and it would unblock the corresponding Spin PR.  Thanks!

2024-10-08 19:44 UTC, rylev approved these changes

2024-10-08 19:45 UTC, merged